#define Phenylalanine "Phenylalanine"
#define Leucine "Leucine"
#define Serine "Serine"
#define Tyrosine "Tyrosine"
#define STOP "STOP"
#define Cysteine "Cysteine"
#define Tryptophan "Tryptophan"
#define Proline "Proline"
#define Histidine "Histidine"
#define Glutamine "Glutamine"
#define Arginine "Arginine"
#define Isoleucine "Isoleucine"
#define Methionine "Methionine"
#define Threonine "Threonine"
#define Asparagine "Asparagine"
#define Valine "Valine"
#define Alanine "Alanine"
#define Asparic_Acid "Aspartic Acid"
#define Glutamic_Acid "Glutamic Acid"
#define Glycine "Glycine"
#define Lysine "Lysine"